// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"
)

type SatScore struct {
	ID        int64         `json:"id"`
	Name      string        `json:"name"`
	Address   string        `json:"address"`
	City      string        `json:"city"`
	Country   string        `json:"country"`
	Pincode   string        `json:"pincode"`
	SatScore  int64         `json:"sat_score"`
	Passed    bool          `json:"passed"`
	CreatedAt time.Time     `json:"created_at"`
	UpdatedAt time.Time     `json:"updated_at"`
	Rank      sql.NullInt64 `json:"rank"`
}
